apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: demo-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: demo-http
        protocol: HTTP
      hosts:
        - "*.devops.k8s.local"
