apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gke-cluster-chde
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://bitbucket.local.alto.id/scm/iac/gke-cluster.git
    targetRevision: prod
    path: projects/prod-infra-int
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
