apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/app

configMapGenerator:
  - name: demo-configmap
    files:
      - index.html

patches:
  - path: virtual-service-patch.yaml
    target:
      group: networking.istio.io
      kind: VirtualService
      name: vs-hello
      version: v1beta1
