apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: dev-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: dev-local-http
        protocol: HTTP
      hosts:
        - "*.dev.k8s.local"
